export const black = "\x1b[30m"; // Чёрный
export const red = "\x1b[31m"; // Красный
export const blue = "\x1b[34m"; // Синий цвет
export const orange = "\x1b[38;5;214m"; // Оранжевый цвет
export const green = "\x1b[32m"; // Зеленый
export const yellow = "\x1b[33m"; // Желтый
export const magenta = "\x1b[35m"; // Магента
export const cyan = "\x1b[36m"; // Циан
export const white = "\x1b[37m"; // Белый
export const gray = "\x1b[90m"; // Серый
export const lightRed = "\x1b[91m"; // Светло-красный
export const lightGreen = "\x1b[92m"; // Светло-зеленый
export const lightYellow = "\x1b[93m"; // Светло-желтый
export const lightBlue = "\x1b[94m"; // Светло-синий
export const lightMagenta = "\x1b[95m"; // Светло-магентовый
export const lightCyan = "\x1b[96m"; // Светло-циановый
export const reset = "\x1b[0m"; // Сброс цвета
